### PR TITLE
Multi-output New payload

### PR DESCRIPTION
**Pull request by tischla**

### CODE REVIEW

**Comment by njh** [comment]
Thanks! I think this might be related to #22 ?

**Comment by tischla** [comment]
Point 2 of #22 , I think

**Comment by clickworkorange** [comment]
Could this change possibly have caused the broken behaviour seen in https://github.com/njh/node-red-contrib-owfs/issues/24?

**Comment by clickworkorange** [comment]
Ok, did some testing and it's actually _the other way around_; this **fixes** the broken behaviour reported in #24 :)

**Comment by adamgeron** [comment]
I came from from #24.  Supposedly this fixes that, however I can't figure out how to make this fix work.  It doesn't look like there's been a release since the Multi-output New payload was merged into the master.  I even tried downloading the code directly and overwriting the node-module files, but that didn't work either.  What's needed to implement this "fix"?

**Comment by clickworkorange** [comment]
> I even tried downloading the code directly and overwriting the node-module files, but that didn't work either. What's needed to implement this "fix"?

I have to admit I cannot remember what this issue was about, but there's a much better way to roll with node modules pulled from github: you can use the git URL directly in your package.json, or switch an installed module over to the latest github version with NPM like so:
````
npm uninstall some_module; npm install https://github.com/some_user/some_module.git
````
Keep in mind though that being on the bleeding edge can be more trouble than it's worth...

**Pull request merged**
